name: Deploy SSIS Packages

on:
  workflow_dispatch: # Manual trigger

env:
  ISPAC_PATH: "bin/Development/ProjectPackages.ispac"
  SSIS_FOLDER_NAME: "SSISDB/TimesheetDeployedPackages"
  SSIS_PROJECT_NAME: "ProjectPackages"

jobs:
  deploy-ssis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Check File Existence
        run: if not exist "${{ env.ISPAC_PATH }}" echo File not found
        shell: cmd

      - name: Deploy SSIS Package
        run: |
          SSISDeploy.exe -s "${{ env.ISPAC_PATH }}" -d "CATALOG;/${{ env.SSIS_FOLDER_NAME }};${{ secrets.DB_SERVER }}" -at "SQL" -u "${{ secrets.DB_USER }}" -p "${{ secrets.DB_PASSWORD }}" -l INFO;.\ssisdeploy.log
        shell: cmd
