name: Deploy SSIS Packages

on:
  workflow_dispatch: # Manual trigger

env:
  SSIS_PROJECT_PATH: "ProjectPackages/ProjectPackages.dtproj"
  ISPAC_OUTPUT_PATH: "bin/Development"
  SSIS_FOLDER_NAME: "SSISDB/Dev"
  SSIS_PROJECT_NAME: "ProjectPackages"

jobs:
  deploy-ssis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Working Directory
        run: dir
        shell: cmd

      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Build SSIS Project
        run: |
          SSISBuild.exe -p "${{ env.SSIS_PROJECT_PATH }}" -c "Development" -o "${{ env.ISPAC_OUTPUT_PATH }}" -l INFO;.\ssisbuild.log
        shell: cmd

      - name: Deploy SSIS Package
        run: |
          SSISDeploy.exe "${{ env.ISPAC_OUTPUT_PATH }}/ProjectPackages.ispac" -ServerInstance "${{ secrets.DB_SERVER }}" -Catalog SSISDB -Folder "${{ env.SSIS_FOLDER_NAME }}" -ProjectName "${{ env.SSIS_PROJECT_NAME }}" -User "${{ secrets.DB_USER }}" -Password "${{ secrets.DB_PASSWORD }}"
        shell: cmd
