name: Deploy SSIS Packages

on:
  workflow_dispatch: # Manual trigger

env:
  ISPAC_PATH: "ProjectPackages.ispac"  # Path to the pre-built .ispac file
  SSIS_FOLDER_NAME: "SSISDB/Dev"
  SSIS_PROJECT_NAME: "ProjectPackages"

jobs:
  deploy-ssis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Deploy SSIS Package
        run: |
          SSISDeploy.exe "${{ env.ISPAC_PATH }}" -ServerInstance "${{ secrets.DB_SERVER }}" -Catalog SSISDB -Folder "${{ env.SSIS_FOLDER_NAME }}" -ProjectName "${{ env.SSIS_PROJECT_NAME }}" -User "${{ secrets.DB_USER }}" -Password "${{ secrets.DB_PASSWORD }}"
        shell: cmd
