name: Deploy SSIS Packages

on:
  workflow_dispatch: # Manual trigger

env:
  SSIS_PROJECT_PATH: "ProjectPackages/ProjectPackages.dtproj"
  ISPAC_OUTPUT_PATH: "bin/Development" # Adjusted to match your bin/Development directory
  SSIS_SERVER: "LAPTOP-ATT0UPK9"
  SSIS_FOLDER_NAME: "SSISDB/Dev"
  SSIS_PROJECT_NAME: "ProjectPackages"

jobs:
  deploy-ssis:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      - name: Build SSIS Project
        run: |
          SSISBuild.exe ${{ env.SSIS_PROJECT_PATH }} -Configuration Development -OutputFolder ${{ env.ISPAC_OUTPUT_PATH }}
        shell: cmd

      - name: Deploy SSIS Package
        run: |
          SSISDeploy.exe ${{ env.ISPAC_OUTPUT_PATH }}/ProjectPackages.ispac -ServerInstance ${{ env.SSIS_SERVER }} -Catalog SSISDB -Folder ${{ env.SSIS_FOLDER_NAME }} -ProjectName ${{ env.SSIS_PROJECT_NAME }} -User ${{ secrets.SQL_USERNAME }} -Password ${{ secrets.SQL_PASSWORD }}
        shell: cmd
