name: Deploy SQL Server Agent Jobs

on:
  workflow_dispatch:

jobs:
  deploy-sql-agent-jobs:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Directory Contents
        shell: powershell
        run: |
          Write-Host "Listing current directory contents:"
          Get-ChildItem -Recurse

      - name: Deploy SQL Server Agent Jobs
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
        shell: powershell
        run: |
          Write-Host "Starting SQL Server Agent jobs deployment for all packages..."

          $tempJobsPath = "temp-jobs"
          $jobScriptTemplate = "sql/JobScript.sql"
          $stdoutLog = ".\jobdeploy_output.log"
          $stderrLog = ".\jobdeploy_error.log"
          $connectLog = ".\sqlconnect_test.log"

          # Validate template script exists
          if (-not (Test-Path $jobScriptTemplate)) {
              Write-Error "Job script template not found at: $jobScriptTemplate"
              exit 1
          }

          # Create temporary directory for job scripts
          if (-not (Test-Path $tempJobsPath)) {
              New-Item -ItemType Directory -Path $tempJobsPath | Out-Null
          }

          # Test SQL Server connectivity with Windows Authentication
          Write-Host "Testing Windows Authentication connectivity..."
          try {
              $sqlcmd = "sqlcmd -S `"$env:DB_SERVER`" -E -Q `"SELECT @@VERSION`" -o $connectLog"
              Invoke-Expression $sqlcmd
              if ($LASTEXITCODE -eq 0) {
                  Write-Host "Windows Authentication connectivity test succeeded."
                  Get-Content $connectLog | Write-Host
              } else {
                  Write-Error "Windows Authentication connectivity test failed."
                  Get-Content $connectLog | Write-Error
                  exit 1
              }
          } catch {
              Write-Error "Error testing Windows Authentication: $_"
              exit 1
          }

          # Drop existing jobs if they exist
          Write-Host "Attempting to drop existing SQL Server Agent jobs..."
          $packages = sqlcmd -S "$env:DB_SERVER" -E -Q "SELECT name FROM SSISDB.catalog.packages WHERE folder_name = 'TimesheetDeployedPackages' AND name NOT IN ('TimesheetPa', 'TimesheetStaging1')" -h -1 -W
          foreach ($package in $packages.Trim().Split([Environment]::NewLine) | Where-Object { $_ }) {
              $jobName = $package
              try {
                  $sqlcmd = "sqlcmd -S `"$env:DB_SERVER`" -E -Q `"IF EXISTS (SELECT job_id FROM msdb.dbo.sysjobs WHERE name = N'$jobName') EXEC msdb.dbo.sp_delete_job @job_name = N'$jobName';`" -o $connectLog"
                  Invoke-Expression $sqlcmd
                  if ($LASTEXITCODE -eq 0) {
                      Write-Host "Existing job '$jobName' dropped successfully or did not exist."
                      Get-Content $connectLog | Write-Host
                  } else {
                      Write-Warning "Failed to drop existing job '$jobName'. Continuing with deployment..."
                      Get-Content $connectLog | Write-Warning
                  }
              } catch {
                  Write-Warning "Error dropping existing job '$jobName': $_"
              }
          }

          # Generate and deploy jobs for all packages except TimesheetPa and TimesheetStaging1
          Write-Host "Generating and deploying SQL Server Agent jobs..."
          $packages = sqlcmd -S "$env:DB_SERVER" -E -Q "SELECT name FROM SSISDB.catalog.packages WHERE folder_name = 'TimesheetDeployedPackages' AND name NOT IN ('TimesheetPa', 'TimesheetStaging1')" -h -1 -W
          if (-not $packages) {
              Write-Error "No packages found in SSISDB/TimesheetDeployedPackages excluding TimesheetPa and TimesheetStaging1"
              exit 1
          }

          foreach ($package in $packages.Trim().Split([Environment]::NewLine) | Where-Object { $_ }) {
              $jobName = $package
              $scriptPath = Join-Path $tempJobsPath "$jobName.sql"

              # Read the template and replace placeholders
              $templateContent = Get-Content -Path $jobScriptTemplate -Raw
              $scriptContent = $templateContent -replace '@jobName', $jobName -replace 'LAPTOP-ATT0UPK9', $env:DB_SERVER

              # Debug: Write the script content to verify
              Write-Host "Generated script content for $jobName.sql:"
              $scriptContent | Write-Host
              $scriptContent | Out-File -FilePath $scriptPath -Encoding UTF8 -NoNewline

              Write-Host "Deploying job script: $scriptPath"
              try {
                  $sqlcmd = "sqlcmd -S `"$env:DB_SERVER`" -E -i `"$scriptPath`" -o $stdoutLog -e"
                  Invoke-Expression $sqlcmd
                  if ($LASTEXITCODE -eq 0) {
                      Write-Host "Successfully deployed job script: $jobName.sql"
                      Get-Content $stdoutLog | Write-Host
                  } else {
                      Write-Error "Failed to deploy job script: $jobName.sql"
                      Get-Content $stdoutLog | Write-Error
                      if (Test-Path $stderrLog) { Get-Content $stderrLog | Write-Error }
                      exit 1
                  }
              } catch {
                  Write-Error "Error deploying job script $jobName.sql: $_"
                  exit 1
              }
          }

          Write-Host "All SQL Server Agent jobs deployed successfully."
          exit 0
