# .github/workflows/main-deploy.yml
name: Main Deployment Workflow

on:
  workflow_dispatch:

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and Run SQLCMD
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          export PATH="$PATH:/opt/mssql-tools/bin"
          sqlcmd -S $DB_SERVER -U $DB_USER -P $DB_PASSWORD -i sql/TimesheetDB.sql
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

  trigger-ssis-and-jobs:
    needs: deploy-database
    uses: ./.github/workflows/ssis-deploy.yml
    secrets: inherit
